import React from "react";
const ListOfTypesOfCars=[
    {typeOfCar:'compact',heading:'Rental Compact Cars',paragraph:'Choose from a variety of rental cars in this category including economy, full-size or luxury sedans. Whether you are looking for fuel-efficiency, space, or comfort and style you are sure to find the perfect rental car no matter whether you are going on a quick family visit or an adventurous road trip.'},
    {typeOfCar:'luxury',heading:'Luxury Rental Cars',paragraph:'Looking for an upscale driving experience? Our luxury rental cars have plenty of power, modern technology, and creature comforts, making them perfect for business travel or long trips.'},
    {typeOfCar:'SUV',heading:'Rental SUVs',paragraph:'Our SUVs offer plenty of flexibility with seating capacity, power, and luggage room. Whether you are going on a weekend road trip or exploring the countryside we are sure to have the ideal SUV for your needs.'},
    {typeOfCar:'vans',heading:'Rental Vans',paragraph:'Need extra room for people, luggage, or cargo or both? Our minivans and passenger vans can seat up to 7 and 15 passengers respectively and are great for family vacations or accommodating large groups. Cargo vans are ideal for transporting bulky items that may not fit in your personal vehicle.'},
    {typeOfCar:'truck',heading:'Rental Trucks',paragraph:'Whether you’re hauling large items for a DIY project or packing up for a weekend retreat, our pickup trucks have the space, power and durability ideal for your needs. Rent-A-Car locations do not allow a hitch to be attached or towing of any kind with the rental vehicle.'},
    {typeOfCar:'awd',heading:'4x4 Rental Cars',paragraph:'Browse our selection of AWD and 4x4 rental cars for your next adventure. Whether you are traveling for business or taking a family vacation, our selection of all-wheel drive and 4x4 vehicles will help you get there.'}
];
export default ListOfTypesOfCars;